// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ListDir(arg1:string):Promise<Array<main.FileInfo>>;

export function Mkdir(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;
